# Generated by Django 3.0.5 on 2021-05-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='Product ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Cost')),
                ('price_regular', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('price_platinum', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('price_vvip', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('price_wholesale', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('product_type', models.IntegerField(choices=[(1, 'Accessories'), (2, 'Backs'), (3, 'Batteries'), (4, 'Cables'), (5, 'Cases'), (6, 'Parts'), (7, 'Phones'), (8, 'Screens'), (9, 'Tempered Glasses'), (10, 'Tools'), (11, 'Used')], verbose_name='Type')),
                ('own_formula_regular', models.CharField(blank=True, max_length=100)),
                ('own_formula_platinum', models.CharField(blank=True, max_length=100)),
                ('own_formula_vvip', models.CharField(blank=True, max_length=100)),
                ('own_formula_wholesale', models.CharField(blank=True, max_length=100)),
                ('use_own_formula', models.BooleanField(default=False)),
            ],
        ),
    ]
