# Generated by Django 3.0.5 on 2021-05-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_update', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.IntegerField(default=1, verbose_name='Model ID'),
            preserve_default=False,
        ),
    ]
