# Generated by Django 3.0.5 on 2021-05-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_update', '0002_auto_20210518_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='own_formula_platinum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='own_formula_regular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='own_formula_vvip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='own_formula_wholesale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_platinum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_regular',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_vvip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_wholesale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.IntegerField(choices=[(1, 'Accessories'), (2, 'Backs'), (3, 'Batteries'), (4, 'Cables'), (5, 'Cases'), (6, 'Parts'), (7, 'Phones'), (8, 'Screens'), (9, 'Tempered Glasses'), (10, 'Tools'), (11, 'Used')], null=True, verbose_name='Type'),
        ),
    ]
