# Generated by Django 3.0.5 on 2021-05-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_update', '0003_auto_20210518_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Backs', 'Backs'), ('Batteries', 'Batteries'), ('Cables', 'Cables'), ('Cases', 'Cases'), ('Parts', 'Parts'), ('Phones', 'Phones'), ('Screens', 'Screens'), ('Tempered_Glasses', 'Tempered Glasses'), ('Tools', 'Tools'), ('Used', 'Used')], max_length=20, null=True, verbose_name='Type'),
        ),
    ]
