# Generated by Django 3.0.5 on 2021-05-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_update', '0004_auto_20210519_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=222, verbose_name='Product Name'),
        ),
    ]
