# Generated by Django 3.2.3 on 2021-05-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_update', '0005_auto_20210519_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='New Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Original Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.IntegerField(unique=True, verbose_name='Model ID'),
        ),
    ]
